name: Build and scan rocks, save and send scan reports

on:
  workflow_dispatch:
  # Disable scheduling since ATM it's not working and this should be refactored
  # be refactored as part of https://github.com/canonical/bundle-kubeflow/issues/782.
  # Add `workflow_dispatch` since otherwise the workflow will be invalid.
  # schedule:
  # every day at 1:12AM UTC
  # - cron: '12 1 * * *'
  #   secrets:
  #     CVE_REPORT_JIRA_URL:
  #       required: true

jobs:
  build-scan-rocks:
    name: Build and scan rocks
    strategy:
      matrix:
        rock:
          - api-server
          - persistenceagent
          - scheduledworkflow
          - visualisation-server
          - viewer-crd-controller
          - frontend
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/build_and_scan_rock.yaml@main
    secrets:
      JIRA_URL: ${{ secrets.CVE_REPORT_JIRA_URL }}
    with:
      rock: ${{ matrix.rock }}
