name: CI

on:
  workflow_call:

jobs:
  build:
    name: Build rocks
    runs-on: ubuntu-22.04
    outputs:
      artifact-name:
        description: Name of the directory where rocks are
        default: kfp-operators-rocks
        type: string
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup ROCKs environment
        run: |
          sudo snap install rockcraft
          lxd init --auto

      - name: Build rocks
        run: bash .github/workflows/build-rocks.sh

      - name: Upload rock as artefact
        uses: actions/upload-artifact@v3
        with:
            name: ${{ outputs.artifact-name }}
            path: ~/${{ outputs.artifact-name }}

  integration:
    name: Run remote repository integration tests
    runs-on: ubuntu-22.04
    steps:
      - name: Download rocks
        uses: actions/download-artiact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}

      - name: Import images to microk8s cache
        run: bash .github/workflows/import-rocks.sh
